// Code generated by file2byteslice. DO NOT EDIT.
// (gofmt is fine after generating)

package shaders

var light_go = []byte("// build +ignore\npackage shaders\n\nvar LightColor vec3\nvar LightPoint vec2\n\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\n\tdistance := length(LightPoint*16 - position.xy*16)\n\tattenuation := 1.0 / distance\n\tcol := vec4(attenuation, attenuation, attenuation, pow(attenuation, 3)) * vec4(LightColor, 1)\n\treturn image0TextureAt(texCoord) + col\n}\n")
